### ISSUE TITLE
http_build_query() uses NULL as the 2nd parameter

### ISSUE THREAD

**Issue by adavin** [shift4developer/shift4-php#7]
Using the 2nd parameter in http_build_query() produces the following:

`Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated`

This can be found in `lib/Shift4/Util/ObjectSerializer.php` on Line 76.

**Comment by el-dot** [comment]
Thank you for a feedback and ready to merge PR.
Changes were released with [version 3.0.1](https://github.com/shift4developer/shift4-php/releases/tag/v3.0.1)
